- CrewChiefEx/CrewChiefEx.py
- CrewChiefEx/sim_info.py
- CrewChiefV4.sln
- CrewChiefV4/ACS/ACSData.cs
- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/ACS/ACSSpotter.cs
- CrewChiefV4/CrewChief.cs
Latest update.
There is a small issue when going to pause where it wants to restart session, if the session is timed.
Also CrewChiefV4.sln had its VS version changed, but that should not be an issue.(I tryed to revert but it didnt work out)
> Assettocorsa

- CrewChiefEx/CrewChiefEx.py
- CrewChiefEx/sim_info.py
- CrewChiefV4/ACS/ACSData.cs
- CrewChiefV4/ACS/ACSGameStateMapper.cs
Hi, this should fix some timing issues and session tracking issues thats in the version you currently have. 
Laptime reporting has also been added to this version along with opponent join/leave tracking.
> Assetto Corsa

- CrewChiefV4/ACS/ACSGameStateMapper.cs
Had a bit of an issue with merging the pitstop changes you made.
> merge conflict

- CrewChiefV4/Events/TyreMonitor.cs
I've had this idea, what do you guys think?  Also, if there are other candidates for similar tweaks, let me know.
> Randomize tyre status sectors.

- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/Events/LapTimes.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/PCars/PCarsGameStateMapper.cs
- CrewChiefV4/R3E/R3EGameStateMapper.cs
- CrewChiefV4/RF1/RF1GameStateMapper.cs
- CrewChiefV4/RF2/RF2GameStateMapper.cs
> scary hacks, the cure may be worse than the disease

- CrewChiefV4/CrewChiefV4.csproj
- CrewChiefV4/R3E/R3EGameStateMapper.cs
- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- CrewChiefV4/commands/CommandMacro.cs
- CrewChiefV4/commands/KeyPresser.cs
- CrewChiefV4/commands/MacroManager.cs
- CrewChiefV4/saved_command_macros.json
- CrewChiefV4/speech_recognition_config.txt
- CrewChiefV4_no_sound_files/CrewChiefV4_setup_project.isl
not really ready to merge but it'll do no harm and it's better than leaving this branch to go rotten
> Keypress macros poc

- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/iRacing/Drivers/Driver.cs
- CrewChiefV4/iRacing/Drivers/DriverLiveInfo.cs
- CrewChiefV4/iRacing/Sim.cs
- CrewChiefV4/iRacing/iRSDKSharp/iRacingSDK.cs
- CrewChiefV4/iRacing/iRacingGameStateMapper.cs
Hope i got it the right way round
> Ac lap behind timing fix

- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/Events/LapCounter.cs
- CrewChiefV4/Events/LapTimes.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/iRacing/Drivers/Driver.cs
- CrewChiefV4/iRacing/Drivers/DriverLiveInfo.cs
- CrewChiefV4/iRacing/Drivers/DriverResults.cs
- CrewChiefV4/iRacing/SessionData.cs
- CrewChiefV4/iRacing/Sim.cs
- CrewChiefV4/iRacing/iRacingData.cs
- CrewChiefV4/iRacing/iRacingGameStateMapper.cs
- CrewChiefV4/iRacing/iRacingSharedMemoryReader.cs
Hope this is the right way round, it allways confuses me.
> Iracing session fixing

- CrewChiefV4/App.config
- CrewChiefV4/ControllerConfiguration.cs
- CrewChiefV4/CrewChief.cs
- CrewChiefV4/Events/DamageReporting.cs
- CrewChiefV4/Events/EngineMonitor.cs
- CrewChiefV4/Events/Fuel.cs
- CrewChiefV4/Events/MandatoryPitStops.cs
- CrewChiefV4/Events/Penalties.cs
- CrewChiefV4/Events/Position.cs
- CrewChiefV4/Events/RaceTime.cs
- CrewChiefV4/Events/Timings.cs
- CrewChiefV4/Events/TyreMonitor.cs
- CrewChiefV4/Properties/AssemblyInfo.cs
- CrewChiefV4/Properties/Settings.Designer.cs
- CrewChiefV4/Properties/Settings.settings
- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- CrewChiefV4/UserSettings.cs
- CrewChiefV4/speech_recognition_config.txt
- CrewChiefV4/ui_text.txt
- CrewChiefV4_no_sound_files/CrewChiefV4_setup_project.isl
- README.txt
- change_log_for_auto_updated.html
accessible by button press or voice command. Doesn't sound great but kinda works. Will need a sound pack update for the single new sound set ("no damage").
Unfortunately I seem to have contaminated this PR with 4.8.1.2 build 'stuff'. Ah well :)
> status reports for overall damage, car status + damage, session status, and all three

- CrewChiefV4/App.config
- CrewChiefV4/CrewChiefV4.csproj
- CrewChiefV4/Properties/Settings.Designer.cs
- CrewChiefV4/Properties/Settings.settings
- CrewChiefV4/RingBufferException.cs
- CrewChiefV4/RingBufferStream.cs
- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/UserInterface/MainWindow.Designer.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- CrewChiefV4/UserSettings.cs
- CrewChiefV4/ui_text.txt
- README.txt
- change_log_for_auto_updated.html
Reworked from Daniel Nowak's fork, uses his code for audio handling but uses the same approach as the naudio playback device selection. Also keeps the old DefaultDevice approach as the default behaviour
> Naudio speech recognition

- CrewChiefV4/App.config
- CrewChiefV4/CrewChief.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/Properties/Settings.Designer.cs
- CrewChiefV4/Properties/Settings.settings
- CrewChiefV4/ui_text.txt
- README.txt
first cut of a non-linq version of sortClassPositions. Needs careful review as it could end very badly :)
> reworked sorting so it doesn't use any funky stuff

- CrewChiefV4/Events/LapCounter.cs
- CrewChiefV4/Events/Position.cs
- CrewChiefV4/Events/Timings.cs
- CrewChiefV4/QueuedMessage.cs
needed to extend the delayed message resolution stuff a bit to support this
> Delayed gap resolution

- CrewChiefV4/iRacing/Sim.cs
use the lap distance position in race sessions until we cross the line
> Iracing race end position fix

- CrewChiefV4/CrewChiefV4.csproj
- CrewChiefV4/Events/TyreMonitor.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- CrewChiefV4/Utilities.cs
- CrewChiefV4/packages.config
this uses a quadratic function-fit from the MIT-licensed Numerics library. The fit is done against the wear data for the tyre with the greatest wear.
The quadratic fit appears to be sensible when we have enough data (wear > 20%), but the estimates aren't great below this
> Tyre wear curve fitting

- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/Audio/AudioPlayer.cs
- CrewChiefV4/Events/SmokeTest.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/PCars/PCarsGameStateMapper.cs
- CrewChiefV4/PCars2/PCars2GameStateMapper.cs
- CrewChiefV4/R3E/R3EGameStateMapper.cs
- CrewChiefV4/RF1/RF1GameStateMapper.cs
- CrewChiefV4/RF2/RF2GameStateMapper.cs
- CrewChiefV4/iRacing/iRacingGameStateMapper.cs
this also includes a change to the audio player that closes the channel if we've paused the queue
> update hard parts data for each lap and use it if this is the best lap

- CrewChiefV4/ACS/ACSGameStateMapper.cs
- CrewChiefV4/Audio/AudioPlayer.cs
- CrewChiefV4/CrewChief.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/PCars/PCarsGameStateMapper.cs
- CrewChiefV4/PCars2/PCars2GameStateMapper.cs
- CrewChiefV4/R3E/R3EGameStateMapper.cs
- CrewChiefV4/RF1/RF1GameStateMapper.cs
- CrewChiefV4/RF2/RF2GameStateMapper.cs
- CrewChiefV4/iRacing/iRacingGameStateMapper.cs
reworked the hard parts adjustment & combining process, make the parameter auto-adjust based no the hardness of the track
> Hard parts rework

- CrewChiefV4/Audio/SoundPackVersionsHelper.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- auto_update_data_files/primary/auto_update_data.xml
- auto_update_data_files/secondary/auto_update_data.xml
goal here is to remove all that hard-coded dogshit for sound pack versioning and locations so the application code doesn't need to be aware of any sound pack versioning stuff - it just reads the XML and acts on it
> More downloader rework

- CrewChiefV4/App.config
- CrewChiefV4/Events/IRacingBroadcastMessageEvent.cs
- CrewChiefV4/Properties/Settings.Designer.cs
- CrewChiefV4/Properties/Settings.settings
- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- CrewChiefV4/ui_text.txt
its not ready yet but makes easier to follow
> initial rework

- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/speech_recognition_config.txt
sre language property backwards compatibility
> reinstated deleted property

- CrewChiefV4/SpeechRecogniser.cs
- CrewChiefV4/speech_recognition_config.txt
> This is how we want to check.

- CrewChiefV4/Events/SmokeTest.cs
- CrewChiefV4/UserInterface/MainWindow.Designer.cs
- CrewChiefV4/UserInterface/MainWindow.cs
- ReadMe_Sound_Test.txt
This is to help out MatteAce in debuggin single sounds fragments.
it works for playing folder, names, laptimes sec, hundreds, tenths, gaps, pause and plain numbers. Or a file if first line is path to a valid file name. 
each new line in the text box will add a fragment.
The syntax is:
folder/subfolder
name britton
time {lap,gap.sec,hun,ten} 95.345
pause 100
1207
> WIP smoke test in debug mode

- CrewChiefV4/Events/MulticlassWarnings.cs
Using car class object in all these dictionary objects and stuff felt wrong. Changed it to the car class of string
> map times by class ID instead of class in the multiclass event

- CrewChiefV4/Audio/PlaybackModerator.cs
- CrewChiefV4/CrewChief.cs
- CrewChiefV4/Events/Battery.cs
- CrewChiefV4/Events/Fuel.cs
- CrewChiefV4/Events/LapCounter.cs
- CrewChiefV4/Events/Opponents.cs
- CrewChiefV4/Events/PushNow.cs
- CrewChiefV4/Events/RaceTime.cs
- CrewChiefV4/Events/Timings.cs
- CrewChiefV4/GameState/GameStateData.cs
- CrewChiefV4/GameState/GameStateMapper.cs
when you're lapped, the app still thinks you have to complete the full race distance. This PR aims to address this by introducing a new derived quantity - SessionLapsRemaining. This is the TotalLapsInSession - OverallLeaderCompletedLaps
> Laps remaining rework
